project: Intelligent Prompt Chain
stack:
  backend: .NET 8 + ABP.NET Zero
  frontend: Angular 15+
flows:
  - id: step_0
    name: Generate Project Tree
    input: input/project_structure.txt
    prompt: .ai/prompts/0_tree.prompt.md
    output: output/structure.md

  - id: step_1
    name: Analyze Project Structure
    input: output/structure.md
    prompt: .ai/prompts/1_analysis.prompt.md
    output: output/analysis.md

  - id: step_2
    name: Break Down User Story
    input: input/user_story.yaml
    prompt: .ai/prompts/2_userstory.prompt.md
    output: output/tasks.md

  - id: step_3
    name: Generate Instructions
    input: output/tasks.md
    prompt: .ai/prompts/3_instruction.prompt.md
    output: output/instructions.md

  - id: step_4
    name: Create Test Plan
    input: output/instructions.md
    prompt: .ai/prompts/4_tests.prompt.md
    output: output/test_plan.md

  - id: step_5
    name: DevOps Integration Plan
    input: output/test_plan.md
    prompt: .ai/prompts/5_devops.prompt.md
    output: output/pipeline.yaml
